### ISSUE TITLE
Wrong target in tsconfig

### ISSUE THREAD

**Issue by jeckep** [RussianInvestments/invest-js#7]
A error 

> TypeError: Class constructor ServiceClientImpl cannot be invoked without 'new'
    at new InstrumentsService (/Users/jeckep/projects/github/ts2/node_modules/@tinkoff/invest-js/src/services/InstrumentsService.ts:15:1)
    at new OpenAPIClient (/Users/jeckep/projects/github/ts2/node_modules/@tinkoff/invest-js/src/index.ts:61:24)
    at Object.<anonymous> (/Users/jeckep/projects/github/ts2/src/index.ts:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Module.m._compile (/Users/jeckep/projects/github/ts2/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/jeckep/projects/github/ts2/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

How to reproduce:

1) Create new node project
2) install @tinkoff/invest-js
3) Try to create an object of type OpenAPIClient (like in docs)

How to solve(tested locally):
1) change target in [tsconfig](https://github.com/RussianInvestments/invest-js/blob/main/tsconfig.json) from es5 to es6

**Comment by sradykoff** [comment]
Config updated, please check

**Comment by jeckep** [comment]
thanks. not reproduced in 1.22.1
